# Generated by Django 5.2 on 2025-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_tariff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
        ),
    ]
