# Generated by Django 5.2 on 2025-05-18 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(choices=[('no_exp', 'Нет опыта'), ('1-3', '1-3 года'), ('3-5', '3-5 лет'), ('5+', 'Более 5 лет')], max_length=10)),
                ('desired_salary', models.CharField(choices=[('100', 'до 100 тыс.'), ('200', 'до 200 тыс.'), ('300', 'до 300 тыс.'), ('300+', 'от 300 тыс.')], max_length=10)),
                ('skills', models.TextField(help_text='Навыки через запятую')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
