# Generated by Django 5.2 on 2025-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['created_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='desired_salary',
            field=models.CharField(choices=[('<30k', '<30k'), ('30k-50k', '30k-50k'), ('50k-70k', '50k-70k'), ('70k+', '70k+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('1-2 years', '1-2 years'), ('3-5 years', '3-5 years'), ('5+ years', '5+ years')], max_length=10),
        ),
    ]
